In [1]:
!python --version

Python 3.7.1


In [3]:
import uproot

In [4]:
!wget http://scikit-hep.org/uproot/examples/Zmumu.root

--2019-04-07 15:08:26--  http://scikit-hep.org/uproot/examples/Zmumu.root
Resolving scikit-hep.org (scikit-hep.org)... 192.30.252.153
Connecting to scikit-hep.org (scikit-hep.org)|192.30.252.153|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 178971 (175K) [application/octet-stream]
Saving to: ‘Zmumu.root’

Zmumu.root          100%[===================>] 174.78K   103KB/s    in 1.7s    

2019-04-07 15:08:30 (103 KB/s) - ‘Zmumu.root’ saved [178971/178971]



In [8]:
zmumu = uproot.open("Zmumu.root")['events'].keys()
zmumu

[b'Type',
 b'Run',
 b'Event',
 b'E1',
 b'px1',
 b'py1',
 b'pz1',
 b'pt1',
 b'eta1',
 b'phi1',
 b'Q1',
 b'E2',
 b'px2',
 b'py2',
 b'pz2',
 b'pt2',
 b'eta2',
 b'phi2',
 b'Q2',
 b'M']

In [10]:
tree = uproot.open("Zmumu.root")["events"]
df = tree.pandas.df(["pt1", "eta1", "phi1", "pt2", "eta2", "phi2"])
df

pt1      eta1      phi1      pt2      eta2      phi2
entry                                                          
0      44.7322 -1.217690  2.741260  38.8311 -1.051390 -0.440873
1      38.8311 -1.051390 -0.440873  44.7322 -1.217690  2.741260
2      38.8311 -1.051390 -0.440873  44.7322 -1.217690  2.741260
3      38.8311 -1.051390 -0.440873  44.7322 -1.217690  2.741260
4      27.2981 -0.990688  0.583351  21.8913  1.444340 -2.707650
5      21.8913  1.444340 -2.707650  27.2981 -0.990688  0.583351
6      21.8913  1.444340 -2.707650  27.2981 -0.990688  0.583351
7      21.8913  1.444340 -2.707650  27.2981 -0.990688  0.583351
8      77.0336 -1.140270  0.393582  72.7634 -0.637934 -0.793162
9      72.7634 -0.637934 -0.793162  77.0336 -1.140270  0.393582
10     72.7634 -0.637934 -0.793162  77.0336 -1.140270  0.393582
11     72.7634 -0.637934 -0.793162  77.0336 -1.140270  0.393582
12     44.5173  0.426044 -0.070413  40.6637 -0.525298  2.873290
13     40.6637 -0.525298  2.873290  44.5173  0.426044 -0.070413
14     40.6637 -0.525298  2.873290  44.5173  0.426044 -0.070413
15     40.6637 -0.525298  2.873290  44.5173  0.426044 -0.070413
16     27.4237 -1.368470  0.112680  42.3231 -1.264190 -3.021950
17     42.3231 -1.264190 -3.021950  27.4237 -1.368470  0.112680
18     42.3231 -1.264190 -3.021950  27.4237 -1.368470  0.112680
19     42.3231 -1.264190 -3.021950  27.4237 -1.368470  0.112680
20     35.9165  1.432090 -2.431830  44.8701  0.496169  0.721981
21     44.8701  0.496169  0.721981  35.9165  1.432090 -2.431830
22     44.8701  0.496169  0.721981  35.9165  1.432090 -2.431830
23     44.8701  0.496169  0.721981  35.9165  1.432090 -2.431830
24     36.2136 -0.532520 -1.652390  40.4100  0.836524  1.471740
25     40.4100  0.836524  1.471740  36.2136 -0.532520 -1.652390
26     40.4100  0.836524  1.471740  36.2136 -0.532520 -1.652390
27     40.4100  0.836524  1.471740  36.2136 -0.532520 -1.652390
28     45.5010 -1.558430 -1.624000  30.6742 -0.220038  1.764730
29     30.6742 -0.220038  1.764730  45.5010 -1.558430 -1.624000
...        ...       ...       ...      ...       ...       ...
2274   22.7892  0.283717 -0.731298  30.8493  1.494610  2.793680
2275   22.7892  0.283717 -0.731298  30.8493  1.494610  2.793680
2276   57.6002 -0.562840  2.953590  33.0368 -0.202614 -0.058318
2277   33.0368 -0.202614 -0.058318  57.6002 -0.562840  2.953590
2278   33.0368 -0.202614 -0.058318  57.6002 -0.562840  2.953590
2279   33.0368 -0.202614 -0.058318  57.6002 -0.562840  2.953590
2280   37.0238 -0.541225 -2.911150  53.1578  0.117666  0.809582
2281   53.1578  0.117666  0.809582  37.0238 -0.541225 -2.911150
2282   53.1578  0.117666  0.809582  37.0238 -0.541225 -2.911150
2283   53.1578  0.117666  0.809582  37.0238 -0.541225 -2.911150
2284   31.9470 -0.919537 -0.792207  44.0974  0.610767  1.466140
2285   44.0974  0.610767  1.466140  31.9470 -0.919537 -0.792207
2286   44.0974  0.610767  1.466140  31.9470 -0.919537 -0.792207
2287   44.0974  0.610767  1.466140  31.9470 -0.919537 -0.792207
2288   41.9655 -0.390468  3.077270  48.6344 -0.618444  0.190813
2289   48.6344 -0.618444  0.190813  41.9655 -0.390468  3.077270
2290   48.6344 -0.618444  0.190813  41.9655 -0.390468  3.077270
2291   48.6344 -0.618444  0.190813  41.9655 -0.390468  3.077270
2292   37.0110  1.725080 -1.995740  33.5792  0.324654  1.174330
2293   33.5792  0.324654  1.174330  37.0110  1.725080 -1.995740
2294   33.5792  0.324654  1.174330  37.0110  1.725080 -1.995740
2295   33.5792  0.324654  1.174330  37.0110  1.725080 -1.995740
2296   22.8145 -0.645971 -2.404430  24.1264  0.818806  0.661492
2297   24.1264  0.818806  0.661492  22.8145 -0.645971 -2.404430
2298   24.1264  0.818806  0.661492  22.8145 -0.645971 -2.404430
2299   24.1264  0.818806  0.661492  22.8145 -0.645971 -2.404430
2300   72.8781 -1.482700 -2.775240  32.3997 -1.570440  0.037027
2301   32.3997 -1.570440  0.037027  72.8781 -1.482700 -2.775240
2302   32.3997 -1.570440  0.037027  72.8781 -1.482700 -2.775240
2303   32.3997 -1.570440  0.037027  72.8781

In [15]:
print(df.values.shape)

(2304, 6)


In [23]:
type(df.values[5]),df.values[5]

(numpy.ndarray,
 array([21.8913  ,  1.44434 , -2.70765 , 27.2981  , -0.990688,  0.583351]))

In [29]:
import numpy as np

In [30]:
nda=np.asarray(df.values)
type(nda),nda.shape

(numpy.ndarray, (2304, 6))

In [31]:
nda

array([[ 4.47322e+01, -1.21769e+00,  2.74126e+00,  3.88311e+01,
        -1.05139e+00, -4.40873e-01],
       [ 3.88311e+01, -1.05139e+00, -4.40873e-01,  4.47322e+01,
        -1.21769e+00,  2.74126e+00],
       [ 3.88311e+01, -1.05139e+00, -4.40873e-01,  4.47322e+01,
        -1.21769e+00,  2.74126e+00],
       ...,
       [ 3.23997e+01, -1.57044e+00,  3.70275e-02,  7.28781e+01,
        -1.48270e+00, -2.77524e+00],
       [ 3.23997e+01, -1.57044e+00,  3.70275e-02,  7.28781e+01,
        -1.48270e+00, -2.77524e+00],
       [ 3.23997e+01, -1.57044e+00,  3.70275e-02,  7.28781e+01,
        -1.48270e+00, -2.77524e+00]])

In [24]:
import h5py

In [32]:
fp = h5py.File('zmumu_data.hdf5', 'w')
fp.create_dataset('dataset_1', data=nda)

<HDF5 dataset "dataset_1": shape (2304, 6), type "<f8">

In [33]:
fp.close()

In [34]:
fp2 = h5py.File('zmumu_data.hdf5','r')
b = fp2['dataset_1'][:]
fp2.close()
b

array([[ 4.47322e+01, -1.21769e+00,  2.74126e+00,  3.88311e+01,
        -1.05139e+00, -4.40873e-01],
       [ 3.88311e+01, -1.05139e+00, -4.40873e-01,  4.47322e+01,
        -1.21769e+00,  2.74126e+00],
       [ 3.88311e+01, -1.05139e+00, -4.40873e-01,  4.47322e+01,
        -1.21769e+00,  2.74126e+00],
       ...,
       [ 3.23997e+01, -1.57044e+00,  3.70275e-02,  7.28781e+01,
        -1.48270e+00, -2.77524e+00],
       [ 3.23997e+01, -1.57044e+00,  3.70275e-02,  7.28781e+01,
        -1.48270e+00, -2.77524e+00],
       [ 3.23997e+01, -1.57044e+00,  3.70275e-02,  7.28781e+01,
        -1.48270e+00, -2.77524e+00]])

In [35]:
b.shape,type(b)

((2304, 6), numpy.ndarray)